Shake 43, SHAKE-56
KulvanovskayaAsya/feed-the-cat pull request #9
Opened 2024-06-10 07:35 UTC by anastasiarebr

- Подключено API практикума
- Добавлена логика регистрации и авторизации. Также при переходе на страницы игры и форума пользователя без авторизации редиректит на форму логина
- Добавлен HOC для проверки авторизации

2024-06-10 08:35 UTC, KulvanovskayaAsya reviewed
Проделана хорошая и аккуратная работа, несколько небольших замечаний можно найти в комментариях к коду

2024-06-10 08:35 UTC, KulvanovskayaAsya commented on packages/client/src/api/base-api.ts
> +  }
Возможно, стоит вынести общие параметры конфигурации, такие как withCredentials: true, в конфиг BaseAPI

Пример:
  private a: AxiosInstance

  constructor() {
    this.a = axios.create({
      baseURL: HTTPS,
      withCredentials: true
    })
  }

2024-06-10 08:35 UTC, KulvanovskayaAsya commented on packages/client/src/pages/Login/LoginPage.tsx
> +
Стоит рассмотреть мемоизацию функции

2024-06-10 08:35 UTC, KulvanovskayaAsya commented on packages/client/src/pages/index.ts
> +} from './ForumTopicCreation'
Я не уверена, что "WithAuth" стоит добавлять к названию каждого компонента-страницы, тк авторизация глобальна для всего приложения и наши страницы будут работать и без нее

2024-06-10 08:35 UTC, KulvanovskayaAsya commented on packages/client/src/utils/HOCs/withAuth.tsx
> +    let isAuth = false
Переменная isAuth не является состоянием, поэтому её изменение не вызывает перерисовку компонента. Это может привести к некорректному поведению компонентов, обернутых в hoc
const [isAuth, setIsAuth] = useState<boolean | null>(null)

2024-06-10 08:35 UTC, KulvanovskayaAsya commented on packages/client/src/utils/HOCs/withAuth.tsx
> +    }, [])
Лучше разделить на два хука, тк не все зависимости указаны в текущей реализации. Нужно всегда в полном объеме указывать зависимости хука. Так, логику редиректа при смене isAuth лучше отделить и указать зависимости

2024-06-10 13:00 UTC, prjanja commented on package.json
> +    "axios": "^1.7.2"
Лучше эту зависимость установить не глобально, а только для пакета `client`

2024-06-10 13:00 UTC, prjanja commented on packages/client/src/pages/index.ts
> +} from './ForumTopicCreation'
Согласен с тем, что HOC тут лишний. Если хочется сделать защищенные пути, то можно использовать [такой подход](https://stackoverflow.com/a/76683881/14207720)

2024-06-10 21:36 UTC, unreal-zorro commented on packages/client/src/utils/HOCs/withAuth.tsx
> +import React, { FC, useEffect } from 'react'
Думаю, что не нужно при переходе на каждую страницу делать вызов await authController.getUser().
Можно упростить данный компонент, а информацию о том, авторизован ли пользователь, можно брать например из контекста (в дальнейшем из redux):

```
import { Navigate, Outlet, useLocation } from 'react-router-dom'
import { useAuthContext } from '@/context'

export const WithAuth = (): JSX.Element => {
  const location = useLocation()
  const { authData } = useAuthContext()

  if (!authData.isAuth) {
    return <Navigate to="/login" state={{ from: location }} replace />
  }

  return <Outlet />
}
```

2024-06-10 21:36 UTC, unreal-zorro commented on packages/client/src/pages/index.ts
> +} from './ForumTopicCreation'
Можно сделать примерно так, если использовать WithAuth в коде ниже:

```
import { type FC } from 'react'
import { useRoutes } from 'react-router-dom'
import * as Pages from '../pages'
import { BaseLayout } from '@/layouts/BaseLayout'
import { WithAuth } from '@/utils/HOCs/withAuth'

const routes = [
  {
    path: '/',
    element: <BaseLayout />,
    children: [
      {
        index: true,
        element: <Pages.HomePage />,
      },
      {
        path: '/login',
        element: <Pages.LoginPage />,
      },
      {
        path: '/registration',
        element: <Pages.RegistrationPage />,
      },
      {
        path: '',
        element: <WithAuth />,
        children: [
          { path: '/game', element: <Pages.GamePage /> },
          { path: '/profile', element: <Pages.ProfilePage /> },
          {
            path: '/leaderboard',
            element: <Pages.LeaderboardPage />,
          },
          {
            path: '/forum',
            element: <Pages.ForumPage />,
          },
          {
            path: '/forum/topic/:topicId',
            element: <Pages.ForumTopicPage />,
          },
          {
            path: '/forum/topic/create',
            element: <Pages.ForumTopicCreationPage />,
          },
        ],
      },
      {
        path: '*',
        element: <Pages.Error404Page />,
      },
    ],
  },
]

const AppRoutes: FC = () => useRoutes(routes)

export default AppRoutes
```

2024-06-10 21:36 UTC, unreal-zorro commented on packages/client/src/pages/Login/LoginPage.tsx
> +
Если использовать контекст, то можно при логине класть в него информацию о том, что пользователь авторизован, например так:

```
  const { setAuthData } = useAuthContext()

  const onFinish = async (data: unknown) => {
    setIsLoading(true)
    const res = await authController.signinUser(data as SignInRequest)
    setIsLoading(false)
    if (res instanceof AxiosError && res.response?.data.reason) {
      api.error({
        message: res.response?.data.reason,
      })

      if (res.response?.data.reason === 'User already in system') {
        setAuthData((prevAuthData: AuthData) => {
          return { ...prevAuthData, isAuth: true }
        })
      } else {
        setAuthData((prevAuthData: AuthData) => {
          return { ...prevAuthData, isAuth: false }
        })
      }

      return
    }

    setAuthData((prevAuthData: AuthData) => {
      return { ...prevAuthData, isAuth: true }
    })

    navigation('/profile')
  }
```

Это пример AuthContext:

```
import { createContext, Dispatch, SetStateAction, useContext } from 'react'

export interface AuthData {
  isAuth: boolean
}

export const initialAuthData: AuthData = {
  isAuth: false,
}

export interface AuthContextType {
  authData: AuthData
  setAuthData: Dispatch<SetStateAction<AuthData>>
}

export const AuthContext = createContext<AuthContextType>(
  null as unknown as AuthContextType
)
export const useAuthContext = () => useContext(AuthContext)
```

Его надо подключить в App.tsx, как там сейчас подключен GameContext.

2024-06-10 21:36 UTC, unreal-zorro commented on packages/client/src/pages/Registration/RegistrationPage.tsx
> +  }
Тут аналогично, как на странице с логином:

```
const { setAuthData } = useAuthContext()

  const onFinish = async (data: unknown) => {
    setIsLoading(true)
    const res = await authController.createUser(data as SignUpRequest)
    setIsLoading(false)
    if (res instanceof AxiosError && res.response?.data.reason) {
      api.error({
        message: res.response?.data.reason,
      })

      if (res.response?.data.reason === 'User already in system') {
        setAuthData((prevAuthData: AuthData) => {
          return { ...prevAuthData, isAuth: true }
        })
      } else {
        setAuthData((prevAuthData: AuthData) => {
          return { ...prevAuthData, isAuth: false }
        })
      }

      return
    }

    setAuthData((prevAuthData: AuthData) => {
      return { ...prevAuthData, isAuth: true }
    })

    navigation('/profile')
  }
```

2024-06-11 15:23 UTC, unreal-zorro reviewed
Найдены некоторые ошибки в файле withAuth.tsx

2024-06-11 15:23 UTC, unreal-zorro commented on packages/client/src/utils/HOCs/withAuth.tsx
> +  useCallback(redirect, [location.pathname, authData.isAuth])
Здесь должен быть useEffect, а не useCallback:

`useEffect(redirect, [location.pathname, authData.isAuth])`

2024-06-11 15:23 UTC, unreal-zorro commented on packages/client/src/utils/HOCs/withAuth.tsx
> +  }
Функцию redirect следует изменить, иначе нельзя попасть на главную страницу, нажимая кнопки Вперёд и Назад в браузере:

```
  const redirect = () => {
    if (!authData.isAuth && !isLoginPage) {
      navigate('/')
    }
  }
```

Только при обновлении страницы в браузере пользователя перебрасывает на главную страницу.

2024-06-11 15:23 UTC, unreal-zorro commented on packages/client/src/utils/HOCs/withAuth.tsx
> +      if (isLoginPage) {
Данное условие следует изменить на:

`if (authData.isAuth && isLoginPage) {`

потому что неправильно работает передвижение по истории браузера кнопками Вперёд и назад.

2024-06-11 16:13 UTC, unreal-zorro approved these changes
Ставлю approve, т.к. замечания не значитеьные!

2024-06-12 18:23 UTC, IvanPeleshok requested changes
Добрый день
Классно потрудились
Оставил пару замечаний, предлагаю доработать

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/api/auth-api.ts
> +    const res = await this.post('/auth/signup', body)
Предлагаю не сокращать наименование переменных, т.к код пишется для людей
`response`

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/api/base-api.ts
> +  private a: AxiosInstance
Предлагаю назвать таким образом, чтобы было понятно по контекстному названию
`instance`

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/api/auth-api.ts
> +  async signup(body: SignUpRequest): Promise<SignUpResponse> {
Такое ощущение, что ответ будет содержать другой интерфейс
К примеру, `AxiosResponse<T>`

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/controllers/auth.ts
> +    try {
Здорово, что пользуетесь последним синтаксисом языка

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/pages/Login/LoginPage.tsx
> +  const [data, setData] = useState({
```
useState<SignInRequest>

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/pages/Login/LoginPage.tsx
> +    () =>
Предлагаю использовать с помощью стрелочных, если не требуется доступ к контексту и т.д
```
() => (body: SignInRequest) => !isEqual(body, data)

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/pages/Login/LoginPage.tsx
> +    const res = await authController.signinUser(body as SignInRequest)
response

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/pages/Login/LoginPage.tsx
> +        message: res.response?.data.reason,
Избыточно `.?`, т.к есть проверка выше

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/pages/Registration/RegistrationPage.tsx
> +import { isEqual } from 'lodash'
Хорошим тоном бы было импортировать только isEqual
import isEqual from 'lodash/isEqual'

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/utils/HOCs/withAuth.tsx
> +  const isLoginPage = ['/login', '/registration'].includes(location.pathname)
Было бы здорово вынести в константы /login', '/registration'
Уверен, что где-нибудь в проекте ещё используются

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/utils/HOCs/withAuth.tsx
> +    } else {
Для того, чтобы код был плоским, предлагаю реализовать ранний выход
```
if () {
  ...
  return
}

// else

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/utils/HOCs/withAuth.tsx
> +  } else {
От else можно избавиться, т.е есть ранний выход

2024-06-12 18:23 UTC, IvanPeleshok commented on packages/client/src/App.tsx
> +    <AuthContext.Provider value={{ authData, setAuthData }}>
В дальнейшем предлагаю уйти от контекста, заменив функционалом из стейтменеджера
Т.к работа с контекстам должно строго регулироваться с точки зрения оптимизации

2024-06-13 15:29 UTC, IvanPeleshok approved these changes
Поздравляю, апрув
Оставил некритическое замечание, которое доведёт ваш код до отличного состояния
Прекрасно поработали, хорошего дня :)

2024-06-13 15:29 UTC, IvanPeleshok commented on packages/client/src/api/urls.ts
> +export const HTTPS = 'https://ya-praktikum.tech/api/v2'
При первой проверке не заметил

Предлагаю дать более понятное по наименование название переменной:
```
YANDEX_API

2024-06-13 15:38 UTC, merged